<a href="https://colab.research.google.com/github/jibintom/Machine-Learning-Codebasics-/blob/main/a20.%20Ensemble%20Learning%20-%20Bagging/Ensemble_Learning_Bagging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ensemble Learning: Bagging Tutorial**

We will use pima indian diabetes dataset to predict if a person has a diabetes or not based on certain features such as blood pressure, skin thickness, age etc. We will train a standalone model first and then use bagging ensemble technique to check how it can improve the performance of the model

In [18]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

df=pd.read_csv("diabetes_20.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [19]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [20]:
df.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [21]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

**Train and test the data**

In [22]:
x=df.drop("Outcome", axis=1)
y=df.Outcome

In [23]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_ss=ss.fit_transform(x)
x_ss[:3]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.69289057,
        -1.10325546,  0.60439732, -0.10558415]])

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_ss,y, stratify=y, random_state=10) 

**Train using stand alone model**

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

scores=cross_val_score(DecisionTreeClassifier(),x,y, cv=5)
scores

array([0.69480519, 0.64935065, 0.71428571, 0.78431373, 0.7254902 ])

In [26]:
import numpy as np

np.mean(scores)

0.7136490960020372

**Train using Bagging**

In [28]:
from sklearn.ensemble import BaggingClassifier
bag_clf=BaggingClassifier(base_estimator=DecisionTreeClassifier(),
                          n_estimators=100, 
                          random_state=0,
                          max_samples=.8,
                          oob_score=True)
bag_clf.fit(x_train,y_train)
bag_clf.oob_score_

0.7534722222222222

In [29]:
bag_clf.score(x_test,y_test)

0.7760416666666666

**#using cross val score**

In [30]:
from sklearn.ensemble import BaggingClassifier
bag_clf=BaggingClassifier(base_estimator=DecisionTreeClassifier(),
                          n_estimators=100, 
                          random_state=0,
                          max_samples=.8,
                          oob_score=True)

from sklearn.model_selection import cross_val_score
scores=cross_val_score(bag_clf, x,y, cv=5)
scores

array([0.75324675, 0.72727273, 0.74675325, 0.82352941, 0.73856209])

In [32]:
np.mean(scores)

0.7578728461081402

We can see some improvement in test score with bagging classifier as compared to a standalone classifier

**Train using Random Forest**

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

scores=cross_val_score(RandomForestClassifier(n_estimators=50),x,y, cv=5) 
scores

array([0.75324675, 0.74675325, 0.75974026, 0.79084967, 0.75816993])

In [34]:
np.mean(scores)

0.7617519735166793