<a href="https://colab.research.google.com/github/jibintom/Machine-Learning-Codebasics-/blob/main/4.%20Save%20Model%20Using%20Joblib%20And%20Pickle/Save_Model_Using_Joblib_And_Pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
model=linear_model.LinearRegression()
model.fit(df[["area"]],df.price)

LinearRegression()

In [7]:
model.coef_

array([135.78767123])

In [8]:
model.intercept_

180616.43835616432

In [9]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

### Save Model To a File Using Python Pickle

In [10]:
import pickle

***saving the file to our local directory***

In [13]:
with open("model_pickle","wb") as file: #wb means writting the file
  pickle.dump(model,file)

***reading the file from our local directory***

In [15]:
with open("model_pickle","rb") as file: #rb reading the file
  mp=pickle.load(file)

In [16]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])


### Save Trained Model Using joblib

In [20]:
from sklearn import externals
import joblib 

In [21]:
joblib.dump(model, 'model_joblib')

['model_joblib']

***Load Saved Model***

In [22]:
mj = joblib.load('model_joblib')

In [24]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])